document.write('<script type="text/javascript" src="Fkd/Utility/applyConstructor.js"></script>\n');
document.write('<script type="text/javascript" src="Fkd/Utility/base.js"></script>\n');
document.write('<script type="text/javascript" src="Fkd/Utility/ErrorMessage.js"></script>\n');
document.write('<script type="text/javascript" src="Fkd/Utility/extend.js"></script>\n');
document.write('<script type="text/javascript" src="Fkd/Utility/inherits.js"></script>\n');
document.write('<script type="text/javascript" src="Fkd/Utility/isInt.js"></script>\n');
document.write('<script type="text/javascript" src="Fkd/Utility/isUInt.js"></script>\n');
document.write('<script type="text/javascript" src="Fkd/Utility/range.js"></script>\n');
document.write('<script type="text/javascript" src="Fkd/GrassToJSTranslator/Translator.js"></script>\n');
